### ISSUE TITLE
Make sure dockerhub rebuilds the image on base image updates

### ISSUE THREAD

**Issue by vdboor** [brainsam/pgbouncer#10]
The current image is 7 months old. It doesn't seem to rebuild when the base alpine image is updated to fix security bugs. You may want to add the "alpine" to the linked repositories to fix this: https://docs.docker.com/docker-hub/builds/#repository-links

**Comment by brainsam** [comment]
Hi, @vdboor!

I've added alpine as linked repository.

**Comment by vdboor** [comment]
Wonderful! Thanks!
