### ISSUE TITLE
Can you release a tagged version?

### ISSUE THREAD

**Issue by nsauro** [brainsam/pgbouncer#5]
Latest is cool, but I'd rather depend on something that is not a moving target

**Comment by gajus** [comment]
@brainsam You are the only one who can do it..

**Comment by brainsam** [comment]
Hi guys! I've added tag for [1.7.2](https://github.com/brainsam/pgbouncer/tree/1.7.2) version and made tag rule on hub.docker.com.

**Comment by ruimarinho** [comment]
@brainsam can you trigger a build update from the pgbouncer git repo?
